name: dev-build-mac

on:
  push:
    branches:
      - lib-build-test

jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 100
      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: $(brew --prefix)
          key: ${{ runner.os }}-homebrew-${{ hashFiles('.config/brew/Brewfile') }}
      - name: Install Dependencies
        run: |
          brew update --preinstall
          brew install ninja range-v3
      - name: Configure MaaCore
        run: |
          mkdir -p build
          cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_XCFRAMEWORK=ON -DBUILD_UNIVERSAL=ON
      - name: Build libMaaCore
        run: cmake --build build --parallel $(sysctl -n hw.ncpu)
      - name: Prepare Library File
        run: |
          mkdir -p libMaaCore
          cmake --install build --prefix libMaaCore
      - name: Comperss Files
        run: |
          7z a -t7z -m0=lzma2 -mx=9 -aoa -mfb=64 -md=32m -ms=on -mhe -r libs.7z libMaaCore/*
      - uses: actions/upload-artifact@v3
        with:
          name: test
          path: libs.7z
